name: Release build

on:
  push:
#    branches:
#    - "release/**"
#  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: actions/setup-python@v5

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          sccache: "true"
          manylinux: auto

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: artifact-linux-${{ matrix.target }}
          path: dist
          if-no-files-found: 'error'
          # since this artifact will be merged, compression is not necessary
          compression-level: '0'

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: actions/setup-python@v5

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          sccache: "true"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: artifact-macos-${{ matrix.target }}
          path: dist
          if-no-files-found: 'error'
          # since this artifact will be merged, compression is not necessary
          compression-level: '0'

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: artifact-sdist
          path: dist
          if-no-files-found: 'error'
          # since this artifact will be merged, compression is not necessary
          compression-level: '0'

  merge:
    name: Create Release Artifact
    runs-on: ubuntu-latest
    needs: [linux, macos, sdist]
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          # Craft expects release assets from github to be a single artifact named after the sha.
          name: ${{ github.sha }}
          pattern: artifact-*
          delete-merged: true
